name: Build pyside6 application for Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install pyside6 pyinstaller

      - name: Build application
        run: |
          pyinstaller --onefile --noconsole --name aadegui main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: aadegui
          path: dist/aadegui.exe
  publish_release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3

      - name: make SHA2-SUMS files
        run: |
          sha256sum artifact/aadegui.exe | awk '{print $1 "  aadegui.exe"}' >> SHA2-256SUMS
          sha512sum artifact/aadegui.exe | awk '{print $1 "  aadegui.exe"}' >> SHA2-512SUMS
      - name: Publish Release
        uses: actions/create-release@v1
        with:
          tag_name: v0.0.2
          release_name: Release v0.0.2
          name: aadegui v0.0.2
          body: |
            This is a pre-release of aadegui.
            It includes the following features:
            - Connects to AADE
            - Creates invoices
          files:
            SHA2-256SUMS
            SHA2-512SUMS
            artifact/aadegui.exe
          draft: false
          prerelease: true
